# Generated by Django 4.2.2 on 2023-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probankapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='name',
            new_name='Investment_Type',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='year',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='bank',
            name='img',
            field=models.ImageField(default=0.002997002997002997, upload_to='pics'),
            preserve_default=False,
        ),
    ]
