# Generated by Django 4.2.2 on 2023-06-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Form',
        ),
    ]
